name: ramin-image-stream
summary: a sample hello world echo program
description: |
      An applet to stream pi camera over http.
version: '0.1.4'
base: core22
confinement: strict
architectures:
  - build-on: arm64


slots:
  pi-camera:
    interface: custom-device
    custom-device: pi-camera-device
    devices:
      - /dev/video0


plugs:
  pi-camera:
    interface: custom-device
    custom-device: pi-camera-device


apps:
  ramin-image-stream:
    command: bin/flask-wrapper
    daemon: simple
    restart-condition: always
    plugs: [
      home,
      network,
      network-bind,
      opengl,
      camera,
      custom-device,
      pi-camera
    ]
    environment:
      FLASK_APP: ./server.py
      LC_ALL: C.UTF-8
      LANG: C.UTF-8


parts:
  python-packages:
    plugin: python
    source: .
    python-requirements: ['requirements.txt']
    stage-packages:
      - libgl1
      - libice6
      - libsm6
      - libx11-6
      - libxext6
      - libxcb1
  
  flask-server:
    plugin: dump
    source: .
    organize:
      server.py: bin/
      flask-wrapper: bin/
